name: First Workflow 
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello this is the first workflow"
      - name: Print goodbye
        run: echo "Done - bye !!"
